### ISSUE TITLE
Not allowing to set non-existing chains in tickets

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#1001]
Bug, high priority. From a script, in a ticket one can upload a non existing chain.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/7665756/55024116-81d4b880-4ffe-11e9-8124-1228cb9286ec.png">

The chain does not exist

**Comment by justinasr** [comment]
Done #1031, however check is on chain request generation, not on ticket creation
