### ISSUE TITLE
Chained request public API not returning anything

### ISSUE THREAD

**Issue by aminnj** [cms-PdmV/cmsPdmV#1010]
Hi, sorry if I'm not using terminology correctly. My goal is to get a list of cmsDriver commands given a dataset name, so I am trying to 
1. convert a dataset name into a chain prepID (`B2G-chain_RunIIWinter15wmLHE_flowLHE2Summer15GS_flowRunIISummer16DR80PremixPUMoriond17_flowRunIISummer16PremixMiniAODv2_flowRunIISummer16NanoAOD-00394`)
2. break up the chain prepID into separate IDs (`"B2G-RunIIWinter15wmLHE-00556","B2G-RunIISummer15GS-00945","B2G-RunIISummer16DR80Premix-00013","B2G-RunIISummer16MiniAODv2-00011","B2G-RunIISummer16NanoAOD-01463"`)
3. For each prepID, I can then fetch driver/setup/test commands. 
This works just fine in the browser when I'm authenticated with SSO. 

For scripting, I'd like to stick to the public API endpoints but it seems I can't do step 2: `public/restapi/chained_requests/get_setup` does not work (while the non-public `restapi/chained_requests/get` does). For example,
[public](https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/get_setup/B2G-chain_RunIIWinter15wmLHE_flowLHE2Summer15GS_flowRunIISummer16DR80PremixPUMoriond17_flowRunIISummer16PremixMiniAODv2_flowRunIISummer16NanoAOD-00394) 
[non-public](https://cms-pdmv.cern.ch/mcm/restapi/chained_requests/get/B2G-chain_RunIIWinter15wmLHE_flowLHE2Summer15GS_flowRunIISummer16DR80PremixPUMoriond17_flowRunIISummer16PremixMiniAODv2_flowRunIISummer16NanoAOD-00394)

The non-public link has an output that includes the constituent prepIDs, but the public link does not return anything. When I intentionally mangle the the long chain ID, the public endpoint complains that it doesn't exist. What could be going on here? (Or maybe there's a less roundabout way to do all of this)

Thanks!

**Comment by justinasr** [comment]
Hello,

Well, public `get_setup` and non-public `get` are two different things. `get` returns the chained request itself where you can see all the requests in chain and `get_setup` returns a shell script that sets up CMSSW environment and runs cmsDriver. Furthermore, that script returns cmsDriver (I might be slightly wrong, I would need to dig into code deeper) only for non-done requests of the chain.

I can add simple `get` to public chained requests api, so you would be able to do `public/restapi/chained_requests/get` and see the contents of chained request.

**Comment by aminnj** [comment]
Hi,

Right, I was using the public `get_setup` as just an example (looking at the full list of public `chained_request` endpoints [here](https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/), probably `get_dict` would be analogous to the non-public `get`) However, all of those public `chained_request` endpoints don't seem to work for me (they output nothing, but still complain when the chainID is invalid).

Anyway, I think a public `chained_requests/get` would be great (provided it works)! Then I should be able to go from dataset name to list of cmsDrivers for all chain steps with a handful of public API calls.

Thanks!
