### ISSUE TITLE
cmsunified user with some special privilege

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#1012]
can you guys please add cmsunified in the special access list I (vlimant) am in already so that we can transition to that account.
mainly for invalidation acknowledgement functionality IMO, but I might be missing something

**Comment by vlimant** [comment]
unless @drkovalskyi  has already made that request

**Comment by drkovalskyi** [comment]
I don't remember if I did or not.

**Comment by srimanob** [comment]
I see "cmsunified" in this list,
https://cms-pdmv.cern.ch/mcm/settings?prepid=allowed_to_acknowledge&page=0&shown=13
Maybe @justinasr already added it.

**Comment by vlimant** [comment]
good. I'll you know here when that list can be reduced to cmsunified

**Comment by justinasr** [comment]
Hello,

`cmsunified` was added to the list on 11th of January, 2019, because @drkovalskyi made this request (email subject: "Access rights to https://cms-pdmv.cern.ch/mcm/")
