### ISSUE TITLE
Can validation on condor (submitted by McM) happen by reading LHE remotely?

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#1014]
One action item from PPD and O&C Meeting on How to handle LHE / GEN / SIM steps in UL campaign

https://docs.google.com/document/d/1a9yeCX_HsIyGD4-bhZY_gLhNWaFmBK_F8bJY2YwfSZ8/edit?usp=sharing

Can validation on condor (submitted by McM) happen by reading LHE remotely?

**Comment by justinasr** [comment]
Hello,

If this is EOS, then it is reachable by condor by default, that's how (and why) GEN checking script output is saved there.

**Comment by lmoureaux** [comment]
All pLHE are stored at CERN and UL has been running smoothly. I don't understand the concern and there is no action item.
