### ISSUE TITLE
DELETE on /restapi/requests/forcecomplete/<wf name>

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#1015]
the api that used to function does not seem to work anymore

for example
https://cms-pdmv.cern.ch/mcm/restapi/requests/forcecomplete/BPH-RunIIFall17GS-00116

**Comment by justinasr** [comment]
Hello,

Just out of curiosity: when was DELETE working on `/restapi/requests/forcecomplete` ?
I do not remember removing anything and DELETE method plainly just does not exist.

**Comment by vlimant** [comment]
I have no clue when it worked last

**Comment by justinasr** [comment]
What is the expected functionality of it? Remove workflow from forcecomplete list?

**Comment by lmoureaux** [comment]
Removing a wf from the force complete list would be prone to race conditions with computing having fetched it but not acknowledged.
