### ISSUE TITLE
Get growth graph link is broken

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#1024]
For example,
https://cms-pdmv.cern.ch/mcm/chained_requests?contains=B2G-RunIIAutumn18DRPremix-00469&page=0&shown=15
Click on the "picture" icon.

Or this function is not available anymore. Thx.

**Comment by justinasr** [comment]
It was added to DEV some time ago to see what it does. Is it needed or the button should be removed?

**Comment by lmoureaux** [comment]
Works for me now (pointing to pMp).
