### ISSUE TITLE
Forbidding to create already existing chains from a ticket

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#1029]
Could creation of duplicated chains be forbidden from a ticket, which tries to create the same chain?

**Comment by pgunnell** [comment]
Example here:

https://cms-pdmv.cern.ch/mcm/chained_requests?contains=EXO-RunIIFall18GS-01924&page=0&shown=15

**Comment by justinasr** [comment]
Done #1031
