### ISSUE TITLE
Adding GEN script checking for RunIISummer1*FSPremix

### ISSUE THREAD

**Issue by qliphy** [cms-PdmV/cmsPdmV#1036]
Currently MC Contacts checked by hand and put logs in MccM gdoc.  I would be more convenient to have this done automatically.

**Comment by qliphy** [comment]
example:  https://cms-pdmv.cern.ch/mcm/mccms?prepid=SUS-2019Jul10-00003&page=0&shown=5223

**Comment by justinasr** [comment]
Done.
