### ISSUE TITLE
Size of dataset shown in McM (low priority)

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#1046]
Would it make sense to have McM showing the size of the produced dataset?

Otherwise, one needs to get this information from DAS, which is down much more often than McM.

**Comment by justinasr** [comment]
This can be added to Stats as it already gets the size together with done events, just discards everything else but events. I am not sure whether McM should have this number as well as it looks useless to the McM context?

**Comment by pgunnell** [comment]
Thanks Justinas! For requests managers, it would be useful to get the size from a list of requests from McM (and not from DAS). If easy to include, I would be in favour of that.
