### ISSUE TITLE
--filein does not show correctly

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#1067]
For example,
https://cms-pdmv.cern.ch/mcm/requests?member_of_chain=SMP-chain_RunIIWinter15pLHE_flowLHE2Summer15GS_flowRunIISummer16DR80PremixPUMoriond17_flowRunIISummer16MiniAODv3_flowRunIISummer16NanoAODv6-00010&page=0&shown=549755814015

DR, Mini, Nano are injected together in the same time but --filein seems strange
Mini ==> filein points to origin of the chain (--filein lhe:19089)
Nano ==> filein points to expected datatier from Mini (?)

This seems to be an issue on showing in McM only, workflow is made properly.

**Comment by lmoureaux** [comment]
Intended behavior: to test NanoAOD only we'd start from the existing Mini.
