### ISSUE TITLE
Multiple request modification: bug with time/event

### ISSUE THREAD

**Issue by swertz** [cms-PdmV/cmsPdmV#1078]
The ability in McM to select several requests and modify some quantities for all of those at once is very useful.

However it doesn't work well for the time/event field: I've tried editing the existing time/event entry or deleting the existing one and creating a new one, but in both cases the original time/event doesn't get removed. Instead, a new entry is added. 

Worse, when applying that change to several selected requests, some requests end up with many duplicate time/event entries (and it seems that, for request validation at least, it's the sum of all those entries that is used)...

**Comment by justinasr** [comment]
Indeed, McM tried to merge old and new list of time/event. Multiple request edit is a tricky feature. Fixed - now time per event will be overwritten to values in editing page, i.e. if one request had 1 and 2 and other 3 and 4 _and_ you set 5, 6 and 7 in editing page, both requests will have 5, 6 and 7 as time per event.
Let me know if you have any more problems with this.

**Comment by swertz** [comment]
Thanks a lot, it works fine now! :+1:

FYI, I've noticed that modifying the event size also doesn't work, it results in multiple empty entries:
![image](https://user-images.githubusercontent.com/8058274/99507042-30233380-2983-11eb-8f20-559842a3af58.png)
(but this is not somthing I need atm)

**Comment by justinasr** [comment]
I added both time/event and size/event into list of "exceptional lists that should not be merged" when fixing time/event for you: https://github.com/cms-PdmV/cmsPdmV/commit/c7dea8ee764a15e6a5fc8a5e6bcc90414a5c2338 so size/even _should_ be good too.

**Comment by swertz** [comment]
I've tried again and I still see this list of 3 empty entries as in the screenshot above.

What's a little strange is that in the multiple edit page, the evens size doesn't appear as a list:
![image](https://user-images.githubusercontent.com/8058274/99643738-5a412800-2a4d-11eb-9bfc-957098a60005.png)

While time/event does, as expected:
![image](https://user-images.githubusercontent.com/8058274/99643844-79d85080-2a4d-11eb-9d46-04c057bca4f4.png)

Anyway, I won't need to change the event size (just the time), I just wanted to report this...

Just for my education, why are event size and time/event represented as lists instead of single entries?

**Comment by justinasr** [comment]
Ah, it was broken in the frontend as well, not just backend. I updated the HTML, so now size/event editing should work correctly.

> Anyway, I won't need to change the event size (just the time), I just wanted to report this...

No no, that's good, thanks for detailed explanation and screenshots.

Changing size/event and time/event to a list predates me, but according to commits https://github.com/cms-PdmV/cmsPdmV/commit/ff55ebb36e42a10020e2b8a129ace9b95f4203ba and https://github.com/cms-PdmV/cmsPdmV/commit/43c33f86447f99e279a6220c4afcee85bca28acf reason is "_When generating taskchain dict each task uses it's dedicated size_event value_" and "_When removing sequence, it removes same index time_event_". It seems that someone wanted more control over each _task's_ time/event and size/event. When requests with multiple sequences are submitted to computing, these multiple sequences act as different _tasks_ event though they come from the same request.

**Comment by swertz** [comment]
Thanks for the clarification and for the fix!
