### ISSUE TITLE
Process string is not propagated to McM

### ISSUE THREAD

**Issue by andreypz** [cms-PdmV/cmsPdmV#1095]
[This request](https://cms-pdmv.cern.ch/mcm/requests?prepid=MUO-Run3Summer22EEDR-00002) should contain a "process string" `Poisson60ForMUOVal` due to the [corresponding flow](https://cms-pdmv.cern.ch/mcm/edit?db_name=flows&prepid=flowRun3Summer22EEDRPoisson60forMuoVal). However it does not appear on McM page.

**Comment by lmoureaux** [comment]
This is explicitly not supported, flows are added to the process string automatically.
