### ISSUE TITLE
Allow `generator_contact` to rename after defined state

### ISSUE THREAD

**Issue by tvami** [cms-PdmV/cmsPdmV#1116]
## Is your feature related to a problem?
Quite often GEN asks us to rename a sample before they approve it. 
One example here https://gitlab.cern.ch/cms-gen/mccm/-/issues/11

In this case we have two options
 * reset the sample, rename, revalidated, put it into defined, inform GEN
 * ask GEN L2s to rename 

The first one is time and resource consuming for no good reason, while the second one is a significant overhead on the GEN L2s and it's also an unnecessary protection given that renaming a sample wont change the physics or the computing behaviour 

## Describe the solution you'd like

Loosen the restriction to rename, minimally allow the `production_manager` to do this, but even better allow the `generator_contact` to do this. GEN ( @menglu21 @bbilin) also supports loosening this restriction.

## Current behavior

Bothering GEN L2s

## Expected behavior

Just do the renaming ourselves

@ggonzr @DickyChant

**Comment by ggonzr** [comment]
Update merged and deployed into production, closing this issue
