### ISSUE TITLE
Clone fields dont show up for EXO-RunIISummer20UL18GEN-01636

### ISSUE THREAD

**Issue by tvami** [cms-PdmV/cmsPdmV#1141]
I'm trying to clone https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=EXO-RunIISummer20UL18GEN-01636&page=0&shown=127
but the fields dont show up
<img width="1564" alt="Screenshot 2024-09-03 at 08 21 53" src="https://github.com/user-attachments/assets/fd374746-7039-4869-9a71-cd33feba2dbd">

## Expected Behavior

Have a long list of campaigns to choose from. Which I actually see with other PrepIDs, so it's not a general problem.

**Comment by ggonzr** [comment]
It takes some time to load. I can see all the fields. Could you try again and wait around 1 minute and let me know if you still see the same problem?

![Screenshot from 2024-09-03 17-42-27](https://github.com/user-attachments/assets/044a3589-39c6-4541-bc5c-e32cbacfa1af)

**Comment by tvami** [comment]
Ah yeah it works now! Thanks @ggonzr
