### ISSUE TITLE
Unavailable tags to slc5:x86_64 in /cvmfs

### ISSUE THREAD

**Issue by ggonzr** [cms-PdmV/cmsPdmV#1168]
Old requests like [HIN-HiWinter13DR53X-00031](https://cms-pdmv-prod.web.cern.ch/mcm/requests?prepid=HIN-HiWinter13DR53X-00031&page=0&shown=127) targeting the architecture `slc5_amd64_gcc462` require `slc5` containers which are not available anymore because the tag has been updated.  This impedes the execution of testing, validation, and upload steps. 

## Expected Behavior
Use `el5:x86_64` containers as this is the new prefix for describing that architecture.

## Possible Solution
Include another replacement for the `os_name` variable in the `get_setup_file2()` function to update the prefix

## Steps to Reproduce
1. Attempt to run the test script for request using the SCRAM architecture `slc5_amd64_gcc462` like the one described at the beginning of the issue

**Comment by vlimant** [comment]
incidentally https://gitlab.cern.ch/cms-ppd/dataset-management/dm-coordination/-/issues/8#note_8674112 ; we were instructed to move forward these requests to a later release, that has slc6 support.
