### ISSUE TITLE
add the locks in the dash board

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#206]

**Comment by vlimant** [comment]
Could someone try to see if that can be done easily ? even in a crude form. there seem to be deadlock poping up from time to time causing funky behaviors

**Comment by anorkus** [comment]
not with current implementation. Also the lock_ids are hashed, so only worthy information would be number of acquired/unreleased locks.

**Comment by vlimant** [comment]
does that count as closed given that there are the number of items in queues ?
