### ISSUE TITLE
bookmark-ability of the dashboard

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/cmsPdmV#597]
https://cms-pdmv.cern.ch/mcm/dashboard is an extremely useful service!

Use case: I'd like to be able to send out urls with plots from the dashboard which can present the same plots I am looking at to someone else. The url should contain all the info to reproduce the campaign I've chose, the settings, variable display etc...

Can we address if / how laborious it would be to support this use case ?

**Comment by AdrianAlan** [comment]
as for #734
