### ISSUE TITLE
bad view queries

### ISSUE THREAD

**Issue by anorkus** [cms-PdmV/cmsPdmV#678]
should return/inform user about the bad/missing view. 
Now couchdb-lucene returns {"code":500} in case of failure. Which is good json for mcm, but it doesn't include any information thus "Found 0" is seen by users.

**Comment by vlimant** [comment]
This should be reopened as inexisting view queries are still returning 0 instead of making a warning

https://cms-pdmv.cern.ch/mcm/requests?type=MCReproc

for example
