### ISSUE TITLE
Setting PrepID per Task in TaskChain

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#697]
tied to completion of https://github.com/dmwm/WMCore/issues/5402 , to close the loop on 568.

**Comment by vlimant** [comment]
We should set PrepID per task in the schema right away to allow for proper labelling and dictionnary documentation. ops has  increasing interest on this.

**Comment by ericvaandering** [comment]
From your mention here https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2358/1.html and looking at the status of the WMCore issues, it seems PdmV can proceed on this issue.

**Comment by vlimant** [comment]
@srimanob for the fastsim campaign that is about to start, that would be very good to have

**Comment by vlimant** [comment]
ping ! This would be very important to have for tracking things. It's a one-liner, do you want me to do a PR ?

**Comment by anorkus** [comment]
a PR is always welcome

**Comment by vlimant** [comment]
Hi @anorkus can you please comment on when is this going to be deployed ? and close the ticket when it does

**Comment by anorkus** [comment]
it was last tuesday
