### ISSUE TITLE
Request with ALCARECO and ACDC not toggling done

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#724]
Because of 
https://github.com/cms-PdmV/cmsPdmV/blob/v1.7.17/mcm/json_layer/request.py#L1629

some request might not toggle to done when there are more complex processing string made from (skims or alcareco).
For example: https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-Phys14DR-00001 is not toggling done

**Comment by srimanob** [comment]
@franzoni @anorkus 
Just to make sure we didn't forget this issue. I will add to the postMccM TWiki for this Thursday.
