### ISSUE TITLE
Is it possible to add McM tags to chained/completed entries?

### ISSUE THREAD

**Issue by covarell** [cms-PdmV/cmsPdmV#727]
Is it possible to add McM tags a posteriori to entries which are already 
completed/chained?

I tried with one request:
https://cms-pdmv.cern.ch/mcm/requests?prepid=BTV-RunIIFall14GS-00002&page=0&shown=127
If I try to edit/commit, the result is "Success" (green) but the tag in 
the end is not added...

**Comment by anorkus** [comment]
Hi,

yes its possible. There is one issue/bug/feature that you encountered. To overcome it: write tag in input field; click comma "," and the string will become like a tag in the input; save the updated request

**Comment by covarell** [comment]
You mean "type ," not "click ,", yes it works, thanks
