### ISSUE TITLE
Can't validate the taskchain request, the wheel spins indefinitely.

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#730]
I try to validate the chain
https://cms-pdmv.cern.ch/mcm/chained_requests?prepid=SMP-chain_Summer12WMLHE_flowLHE2S12_flowS12to53GenValidation-00008&page=0&shown=15

The wheel spins very long, no job submit to the batch.

Any issue on this?

**Comment by srimanob** [comment]
It happens only with
SMP-chain_Summer12WMLHE_flowLHE2S12_flowS12to53GenValidation-00008

not with 
TOP-chain_Summer12WMLHE_flowLHE2S12_flowS12to53GenValidation-00004
SMP-chain_Summer12WMLHE_flowLHE2S12_flowS12to53GenValidation-00009

All need wmLHE + GEN-SIM + DIGI-RECO. The difference is I delete the "wmLHE+GEN-SIM" chain request for the problem one, I think. But it should not effect the validation, I think. As the complete chain (all steps we need) should also do that.

Could you please help?

**Comment by vlimant** [comment]
The dead-lock that was created was not released

https://github.com/cms-PdmV/cmsPdmV/blob/v1.7.23/mcm/rest_api/ChainedRequestActions.py#L534
maybe one can replace
runtest = RunChainValid( crid= args[0] , lock=locker.lock( args[0] ) )
with
with locker.lock( args[0] ) as chainlock:
    runtest = RunChainValid( crid= args[0] , lock=chainlock )
    ... everything of the api call ...
