### ISSUE TITLE
Should we disable auto-submission for taskchain requests which contain DR step?

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#732]
If we have full taskchain request, i.e. wmLHE + GS + DR, when the validation of a chain complete, the status of each request will be
 + wmLHE => Validation
 + GS => Validation
 + DR => Approved (as there is no validation/define for DR)

Then if I didn't move wmLHE/GS to Defined/Approved, i.e. I click "chain validation" before I go to bed, the request will stay in these statuses after complete. Then when RequestsInspect check, it will try to submit DR only.
 => I now click soft reset to DR step. Needed before submission the taskchain?

Should the service check first if approved is for DR, its parent should be in complete status?

**Comment by vlimant** [comment]
There should already be a protection preventing this to happen

**Comment by srimanob** [comment]
I saw SMP-Summer12DR53X-00017 moved to submit this morning, but status was still validation.
The is a log from RequestInspect
{"prepid": "SMP-Summer12DR53X-00017", "results": true}

**Comment by vlimant** [comment]
Hi, the approval was moved to submit, but there was no actual workflow created, due to the restriction. There was no error (results=True), and the status of SMP-Summer12DR53X-00017 was still "approved", until 3:25 when you approved the rest of the chain. RAS.
