### ISSUE TITLE
Create a limited reservation interface

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#733]
to complete #684

**Comment by vlimant** [comment]
A pop-up form the "reserve" button, asking to select a possible last campaign from a drop-down menu, and adding or not adding it at the end of the reserve api call would be best in that case. @srimanob

**Comment by vlimant** [comment]
it must have a "blank" entry in the drop-down to allow for full reservation.
the campaigns in the drop down can be retrieved from the chained_campaign the chained_request is a member of, to make it limited enough and prevent injuries.

**Comment by srimanob** [comment]
This API is available in McM now for the chain request level. We can partially reserve the chain. Thanks to @anorkus 

However, we have two main issues:

(1) When we use this function, it always show warning, for example "Chained request HIG-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-00024 reservation of chain HIG-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-00024 should not go beyond RunIIWinter15GS."
The browser will not show the reserve request, we need to click refresh manually. Do you, @vlimant  , have comment about these line, https://github.com/cms-PdmV/cmsPdmV/blob/490409973d17b4efe4e2de61c33051fbb6430793/mcm/json_layer/chained_request.py#L218-L221

(2) The API should be implemented in the ticket level, so we can avoid working one-by-one request.

**Comment by vlimant** [comment]
the Exception at line 218,221 was the only way I had found to clean exit and make this work. If it can be re-worked into an non exception, that would be the same.
