### ISSUE TITLE
Show up the process_string setup in the flow somewhere in the request configuration

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#735]
When we set the process_string in the flows, i.e.
- https://cms-pdmv.cern.ch/mcm/flows?prepid=flowFall14DR73NoPUPFGS*&page=0&shown=255

Requests:
- https://cms-pdmv.cern.ch/mcm/requests?range=JME-Fall14DR73-00012,JME-Fall14DR73-00013&page=0&shown=2199023255551

People who make requests can't see it (without digging to the flow) that what process_string is define. It should show somewhere for the request. Then when GEN contact modifies the step, and also add additional process_string, they can know exactly how the final processing sting will look like (combine between one in the flow, and one they add).

**Comment by vlimant** [comment]
Hi, I referred to this in the past, when commissioning the "process string" migration.
It should be easy to expose request::get_outputs

https://github.com/cms-PdmV/cmsPdmV/blob/v1.7.23/mcm/json_layer/request.py#L848

through rest and have it display on hoover, or button.
