### ISSUE TITLE
Allow gen contacts/gen convenors to edit limited set of request parameters without resetting

### ISSUE THREAD

**Issue by bendavid** [cms-PdmV/cmsPdmV#740]
As discussed in the postMCCM today, would be useful allow gen contacts and gen convenors to edit a limited subset of request parameters without resetting as long as the request is in status defined or earlier.

The parameters which make sense to be editable are:
Total events
process string
extension
dataset name

**Comment by bendavid** [comment]
Clearly once the request is in status approved, everything should be frozen as now.

**Comment by vlimant** [comment]
Note that for all of those parameters, there are checks done at the new->validation transition which will have to be put at the defined->approved transition.

**Comment by bendavid** [comment]
I would suggest to do the checks at both places even.  The point is not that contacts delay filling in those fields, just that we can change them later if needed.

**Comment by vlimant** [comment]
That was my comment
