### ISSUE TITLE
Add a link to e-log to easily drill down to possible issues

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#750]
adding a link to https://cms-logbook.cern.ch/elog/Workflow+processing/?subtext=HCA-Fall14DR73-00001 for example might help guiding user when noticing stuck request to see that there is something happening.
Link to the replaced by any other tracking system once ops switch to it.

**Comment by franzoni** [comment]
hello JR, thanks for the suggestion, which is a good one.
The logboook is behind a user+password access. Most of the mccm member either don't have an account or have not had a reply (for weeks) to a request of having one. 
We'll ask computing that accounts may be awarded to mccm + interested GEN contacts - or that it's opened to the simple SSO.

**Comment by anorkus** [comment]
will not be implemented. you have to register to read Elog entries, it should have read-only access to everyone in CERN.
