### ISSUE TITLE
McM create two requests with the same prep_id, but from two different chain campaign

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#755]
From: https://cms-pdmv.cern.ch/mcm/chained_requests?contains=JME-RunIIFall14GS-00001&page=0&shown=15 

You can see that "JME-Fall14DR73-00021"s were created twice for 
+ JME-chain_RunIIFall14GS_flowFall14DR73Flat_20_50_50nsPFGSFall14-00001
+ JME-chain_RunIIFall14GS_flowFall14DR73Flat_20_50PFGSFall14-00003

Two chain requests use different flow for DR (25ns and 50ns), but configuration for "JME-Fall14DR73-00021" is based on the one that flow first.

Any hints on this? We have the same issue for From: https://cms-pdmv.cern.ch/mcm/chained_requests?contains=JME-RunIIFall14GS-00003&page=0&shown=15

Since these requests are very urgent, I did a dirty-trick by put Repetition=2 for 25ns chain campaigns. Then I can create "JME-Fall14DR73-00022" with the correct cmsDriver for 25ns.

Thanks.
 Phat-Giovanni

**Comment by anorkus** [comment]
Hi,

here is a check that prevents creation of flows with "_" Which triggered this issue.
https://github.com/cms-PdmV/cmsPdmV/commit/afb856280631de4e84e5d0871704eedbcdb21c0d#diff-77c695ab34d686c6b645dd6b09bff8f1R289
