### ISSUE TITLE
Format of fragment_tag

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#757]
It seems from this line,

https://github.com/cms-PdmV/cmsPdmV/blob/1620d91ea94d6df0639464502a6752baacfa7b96/mcm/HTML/requests.html#L282

It will work (return the correct link to the request page) if we put the fragment_tag in the format,
Configuration/GenProduction/python/name_of_fragment, not only name_of_fragment.

Maybe twiki needs to be fixed:
https://twiki.cern.ch/twiki/bin/view/CMS/PdmVMcMGlossary#requests_name_of_fragment

However, the get_test_command seems to give correct tag for both cases.

Here is an examples,
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-Summer12-02303&page=0&shown=166499191935
+ Name of fragment returns the wrong link
+ get test commands returns the correct link

**Comment by anorkus** [comment]
fixed in https://github.com/cms-PdmV/cmsPdmV/commit/e18514315928f41aebb31c7f47ef66c2b605b88f
