### ISSUE TITLE
Lower rest api NotifyUser to user 

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#762]
https://cms-pdmv.cern.ch/mcm/restapi/requests/notify/ is restricted to generator contacts and up.
For ops, on @pierinim request, ops could send notification of issues to request.
at the same level of https://cms-pdmv.cern.ch/mcm/restapi/notify/ NotifyBatch

**Comment by vlimant** [comment]
Please have this one-liner for next Tuesday so that ops can get easily to the requesters themselves and logging in mcm.

**Comment by anorkus** [comment]
done in: https://github.com/cms-PdmV/cmsPdmV/commit/4c9fc3601e15ae12ff68f90087027e9c1097d695 Should be pulled on Tuesday
