### ISSUE TITLE
No option reset button

### ISSUE THREAD

**Issue by trandbea** [cms-PdmV/cmsPdmV#765]
Hello,

I am a generator contact and signed in as such in McM. I need to do an option reset on a request, but I do not have such a button in my actions column. I can clone, reset, get test, move to next step, etc., but no option reset. 

Any idea why?

Thanks!
Ana

**Comment by anorkus** [comment]
Hi,

for which request(-s) do you see like this? I see "option reset" button on my account with gen_contact permissions.

**Comment by trandbea** [comment]
Here is an example:
https://cms-pdmv.cern.ch/mcm/requests?prepid=SUS-RunIIWinter15wmLHE-00016&page=0&shown=240518496383

**Comment by anorkus** [comment]
4th button from left "Option reset". i see it:
![screen shot 2015-05-26 at 18 55 59](https://cloud.githubusercontent.com/assets/4921271/7817968/ecbfa1f8-03d8-11e5-9785-847386539056.png)

**Comment by trandbea** [comment]
I am afraid I don't.
![screenshot-20152605-095837](https://cloud.githubusercontent.com/assets/9938086/7818020/e60502a4-038d-11e5-8812-a42bef14ddb9.png)
![screenshot-20152605-095816](https://cloud.githubusercontent.com/assets/9938086/7818035/f52369d8-038d-11e5-8b34-5440877fe784.png)

**Comment by anorkus** [comment]
uhh thats even more strange, well i will take a look

**Comment by anorkus** [comment]
hi, 
is it possible that somehow you managed to block "option reset" image on your browser. If you still have this issue (and i assume to all the requests) maybe i could pass by your office and see for myself. Because from the logs i see that everything is fine.

**Comment by trandbea** [comment]
Hi, not sure how one can block an image, but anyway I tried looking at the page in Firefox and indeed the button is there. (I do not see it in either Safari or Chrome.)

Thank you!
