### ISSUE TITLE
Fragment name link broken

### ISSUE THREAD

**Issue by davidsheffield** [cms-PdmV/cmsPdmV#767]
The change e185143 in response to https://github.com/cms-PdmV/cmsPdmV/issues/757 has broken the Fragment Name link for fragments whose names are in the form Configuration/GenProduction/python/ThirteenTeV/name.py. For example, https://cms-pdmv.cern.ch/mcm/requests?prepid=EXO-RunIIWinter15GS-01219&page=0&shown=67239953, which produces a link to genproductions that has an extra "python/" in it.

**Comment by anorkus** [comment]
well, damn. will fix it and should be pulled on the next mcm deployment -> tuesday.

**Comment by vlimant** [comment]
probably worth closing #212 too
