### ISSUE TITLE
Where does "n_per_lhe_test" come from?

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#772]
I'm trying to understand the source of affordable_nevents. 

From the code, 
https://github.com/cms-PdmV/cmsPdmV/blob/e18514315928f41aebb31c7f47ef66c2b605b88f/mcm/json_layer/request.py#L1037-L1047

I see that it's defined like this
affordable_nevents = settings().get_value('n_per_lhe_test')
but I can't find the definition of "n_per_lhe_test".

The issue comes from the request, https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIIWinter15pLHE-00007&page=0&shown=249108103295

It can't pass the validation step, because of 2000000 events are asking of lhetest step.
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/HIG-RunIIWinter15pLHE-00007

**Comment by vlimant** [comment]
https://cms-pdmv.cern.ch/mcm/settings?prepid=n_per_lhe_test is the place that defines the setting 
at https://github.com/cms-PdmV/cmsPdmV/blob/e18514315928f41aebb31c7f47ef66c2b605b88f/mcm/json_layer/request.py#L1901 the test timeout is extended accordingly. A retune of https://cms-pdmv.cern.ch/mcm/settings?prepid=lhe_test_time_event might be necessary with further understanding of the origine of timing excess in running the validation.

**Comment by srimanob** [comment]
Hi @vlimant,

Thanks. I measuring the time/event from HIG and SUS pLHE. It seems HIG uses more time than SUS, but a little less CPU.

@anorkus , @franzoni : Do you think it safe if we reduce 2M events of LHE test to 1.5M for now? I think this can allow the request to be validate.

From HIG-RunIIWinter15pLHE-00007 (can't pass validation)
 Time Summary: 
 - Min event:   1.09673e-05
 - Max event:   0.000878096
 - Avg event:   0.00441158
 - Total job:   44.1158
 CPU Summary: 
 - Min event:   0
 - Max event:   0.002
 - Avg event:   1.28983e-05
 - Total job:   39.595
 - Total event: 0.128983

From SUS-RunIIWinter15pLHE-00001 (can pass validation)
 Time Summary: 
 - Min event:   9.77516e-06
 - Max event:   0.000221014
 - Avg event:   0.000888
 - Total job:   8.88
 CPU Summary: 
 - Min event:   0
 - Max event:   0.002
 - Avg event:   1.42969e-05
 - Total job:   7.28089
 - Total event: 0.142969

**Comment by vlimant** [comment]
Hi @srimanob reducing to 1.5M won't help much if the assumed timing is still a factor 50 more than the usual lhe reading. What is so special about those .lhe files ?
Increasing lhe_test_time_event will help

**Comment by srimanob** [comment]
Hi,

I'm not sure I follow. The 2M events parameter comes from the hard setting of "affordable_nevents". And it caused failure of validation of HIG LHE request, which is the 2nd cmsDriver in  
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/HIG-RunIIWinter15pLHE-00007

Why does changing of lhe_test_time_event will help in this case?

Thanks very much for help.

https://github.com/cms-PdmV/cmsPdmV/blob/e18514315928f41aebb31c7f47ef66c2b605b88f/mcm/json_layer/request.py#L1045-L1047

**Comment by srimanob** [comment]
By the way, I'm trying to change these number. How can I make it active in McM?

**Comment by srimanob** [comment]
OK, the new parameter is now working in int. The proposal from GEN is that we should modify the 2nd cmsRun to depend on the time/event.

**Comment by vlimant** [comment]
the timeout is adapted to all tests. no need to change the sd cmsRun.
