### ISSUE TITLE
Chaining request to be moved from prep-ops HN to a McM action

### ISSUE THREAD

**Issue by covarell** [cms-PdmV/cmsPdmV#777]
Suggestion that the request of chaining a root request to one or more flows is done via a proper "action" button in McM rather than using prep-ops HN, where the traffic is already too high.

Button should be in "Actions" column close to root request and be accessible to all roles above or equal to generator_contact

**Comment by vlimant** [comment]
Hi, this was meant to be handled using MccM tickets already available and can be created by gen contacts, to do exactly what I think you mean.
Some tweaks on privilege might be needed for some of the ticket fields.

**Comment by covarell** [comment]
OK, we do not instruct GEN contacts at the moment to use tickets. Can you point to the relevant documentation?

**Comment by vlimant** [comment]
This https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVMcM#Report is the bare-bone documentation. It probably requires revamping

**Comment by covarell** [comment]
Well, this seems not a viable solution to me... Should the GEN contact him/herself choose the name of the chain in the list? I am afraid no one else than production managers can understand these names and there would be a lot of mistakes... 

I was thinking of some text notification (totally equivalent to a prep-ops HN, but reaching just the relevant people)

**Comment by vlimant** [comment]
If they can choose the chain it's good, if not, the text box can be used to pass on any information that one would pass by HN. The notes of mccms is "some text notification" reaching the prod managers.

**Comment by covarell** [comment]
OK I see

**Comment by covarell** [comment]
Do prod managers agree with this proposal (= GEN contact open tickets and explain which requests need to be chained and you edit it), or will this just create more confusion?
