### ISSUE TITLE
"pref" button doesn't work

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#781]
For example,

I click "perf" of this requests,
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIISpring15DR74-00277&page=0&shown=267128998975

It points to
https://cmsweb.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/pdmvserv_HIG-RunIISpring15DR74-00277_00223_v1__150709_201722_5650

and the result page show "Error: unknown workflow name"

The "output" button shows the proper link,
https://cmsweb.cern.ch/reqmgr/reqMgr/outputDatasetsByRequestName/pdmvserv_HIG-RunIISpring15DR74-00277_00223_v1__150709_201722_5650

Issue with the link?

**Comment by vlimant** [comment]
perf summary is only available for workflow with status >=completed in request manager.
one could add an if in the javascript to not show the perf link in this case.

**Comment by anorkus** [comment]
fixed in https://github.com/cms-PdmV/cmsPdmV/commit/59f910eccfd885926f8740f1c7a0b7d31076ee7e
