### ISSUE TITLE
STEP0ATCERN string can be removed

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#782]
https://github.com/cms-PdmV/cmsPdmV/blob/v1.9.5/mcm/tools/request_to_wma.py#L117

this is not used at at anymore. Running from lhe file at cern is triggered with lheInput from the workflow schema.

**Comment by anorkus** [comment]
removed in https://github.com/cms-PdmV/cmsPdmV/commit/d19bfae86e5365005c5562d849fa4c710ecea023
