### ISSUE TITLE
tags readable even when long

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/cmsPdmV#786]
The tags attached to reqeuts are enclosed inside grey-ish boxes which have a maximum size allowed, preventing the full display of long tags. 
Even when the column to display the tags is extended, the boxes don't extend to fill all the space they could.

Can the size of the tags be made dynamic to reflect the size of the column and take up the sapace available?

**Comment by anorkus** [comment]
the size of tags is dynamic, but it depends on table columns shown and also on display resolution
