### ISSUE TITLE
empty "Get test command"

### ISSUE THREAD

**Issue by perrozzi** [cms-PdmV/cmsPdmV#787]
if I click on "Get test command" for the chain
HIG-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS-00066
I get an empty file
https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/get_test/HIG-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS-00066

reply from Jean-Roch
you can add a gh issue so that adding "?scratch=" would pass the
scratch=True to chained_request.get_setup(...).

https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/1913/1/1/1/1.html

**Comment by anorkus** [comment]
also both requests in chain are in status submitted, thus it returns empty command:
https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/json_layer/chained_request.py#L789
most probably i will remove this line

**Comment by anorkus** [comment]
will be introduced in next mcm update. most probably today evening
