### ISSUE TITLE
Setting time_per_event for each step

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#789]
Following up on this
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2531.html
we should have the time_per_event member being heterogeneous and accept either a single float (backward compatibliity) of a list of float of the same size of the number of steps so as to set properly the time/event for each step. this will benefit the miniaodsim compression and computing efficiency in a bigger picture.

**Comment by anorkus** [comment]
this would mean that after validation all .xlm files (for number of steps) should be parsed and time_event set accordingly?

I would prefer to migrate all requests to have time_event field to use single type (list in this case). Would be cleaner json_layer and no need for complexity. But this would mean migration of whole requests DB.

**Comment by vlimant** [comment]
Hi, is it possible to create a clone db with a replicate rule that sets the time_per_event to a list directly ? that way the migration is rather simple at least for backfilling while working on adapting all that is necessary on where it's used in the code.

**Comment by vlimant** [comment]
Hi, it seems that this item should have higher priority @srimanob
