### ISSUE TITLE
searching

### ISSUE THREAD

**Issue by vveckaln** [cms-PdmV/cmsPdmV#791]
Hello,
I really don't understand how it is possible to search the whole database for datasets at cms-pdmv.cern.ch

1. Which page do I open in the beginning
2. Where do I write the search pattern.

Regards,
Viesturs

**Comment by anorkus** [comment]
Hi,
1st way:
when you go to requests page:
https://cms-pdmv.cern.ch/mcm/requests
then there are few selectable tabs. You select "Output Dataset"
in input you type dataset_name* you want to search.
* wild cards also accepted
2nd way:
edit url
https://cms-pdmv.cern.ch/mcm/requests?produce=/MinBias*&page=0

Best regards,
    Antanas Norkus

**Comment by vveckaln** [comment]
Thanks!
I tried out and it worked well!
Cheers,
Viesturs
