### ISSUE TITLE
Long standing issue with taskchain submission, and how does _task_ replace the whole chain request name

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#793]
@anorkus @vlimant 
Could you please help to understand the issue of submission?

Here is the case (I don’t see Summer15GS in dev yet, so I pass the link on prod):
https://cms-pdmv.cern.ch/mcm/requests?dataset_name=WprimeToWhToWlephtata_narrow_M-1800_13TeV-madgraph&page=0&shown=163212958783

The normal submission doesn’t work when we have 2 requests (one is new, one is approved) share the same ROOT (in approved). Last time, Antanas helped me to look in details, and he found that McM will go to all chain requests related to the same ROOT and it seems if it sees one in NEW, the submission will not happen.

This seems to be another side of the coin with TOP_WMLHE case, where all 3 GEN-SIMs are in approved, then McM submitted 3 chains at once.

I’m trying to use chain-submission (as FastSim request) on specific chain, 2 questions on this:
(1) I’m not sure it will work, as the requests are still in submitted/approved when I wrote this email.
(2) I see the difference if we try to submit taskchain using (i) general way as wmlhe+GS and (ii) chain-submission as FastSim campaign. The difference is workflow name, which is shorten when (i) is used.
- pdmvserv_task_EXO-RunIIWinter15wmLHE-00289__v1_T_150917_194959_4419
- pdmvserv_SUS-chain_RunIIWinter15pLHE_flowRunIISpring15FSPreMix-00002__v1_T_150910_101516_5960 

If I remember correctly, (ii) will not work when workflow name is too long. I think I used to try with 100+ character, then it will not work. Can it be possible that _task_ replace also in (ii)?

For now, I have to delete Summer15GS, then WMLHE + GS in Winter15GS can pass. It's very painful way. And we start to have a long list :/

**Comment by vlimant** [comment]
Is the submission by chain_id functioning in this case ? I suppose it will. Then use this instead of deleting requests and chains.

Or submit by request, the production delays are much less nowadays that taskchain could actually make it slower.

One can probably put the right check and selection for chain submission by request id around https://github.com/cms-PdmV/cmsPdmV/blob/v1.9.9/mcm/tools/handlers.py#L607 to not consider the requests that are not ready to be submitted ; this would be equivalent to use the check_approval to remove a request from submission.

**Comment by srimanob** [comment]
No, the submission by chain_id does not work also, the one that I have done last night still be in submitted/approved.
https://cms-pdmv.cern.ch/mcm/requests?dataset_name=WprimeToWhToWlephtata_narrow_M-1800_13TeV-madgraph&page=0&shown=163212958783

**Comment by srimanob** [comment]
The chain id is too long. If it's not replaced as pdmvserv_task_XXX, I think it's not possible for now. We have a very lucky for FastSim campaign.

len("pdmvserv_EXO-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-00526__v1_T_150918_152157_2365")
128

**Comment by anorkus** [comment]
hmm, do we implement some hashing(shortening of workflow name) which would make harder to follow it up.
Other way we could ask to increase max wf name in computing.

**Comment by srimanob** [comment]
Here is an example of the short one
+ pdmvserv_task_EXO-RunIIWinter15wmLHE-00289__v1_T_150917_194959_4419
which represent
+ EXO-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-00520

**Comment by vlimant** [comment]
So the submission would succeed by chain id, it's only the name that is too long.
provided we have a prepid per task, you should be able to hash the chain_id the way you want it ; to be verified in pdmv stats that nothing depends on the workflow name anymore.
changing to hash and prepid per task might have Dima change a few things to tracking, but nothing major for assignment.

The flow should not have 30 characters each !

**Comment by vlimant** [comment]
One can however consider a smart tuning of the conditions under https://github.com/cms-PdmV/cmsPdmV/blob/v1.9.9/mcm/tools/handlers.py#L607 to support including in submission only those that are in the correct status/approval
