### ISSUE TITLE
actions page: consolidation and extra selection

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/cmsPdmV#799]
(low prio)

the actions page works ok loading prepid's from text file, useful!

The possibility of clikcing to select all the actions of a column should be extend to click both the ticks for a given action (only the first box on the left is clickable for a full column => a lot of one-by-one clicking is left to do to tick the second of the two boxes)

when multiple selections are committed, the spinning icon never stops spinning

The "starts with" and "contains" selectors are delicate: their interplay with the file loading and the sequence of operation deserves some consolidation

**Comment by srimanob** [comment]
We need this mechanism also to help us to delete DRs of multiple requests, since we need to disable the chain request first.
