### ISSUE TITLE
MCM restAPI does not work anymore

### ISSUE THREAD

**Issue by tobias-pook** [cms-PdmV/cmsPdmV#801]
Dear MCM developers.
I am not sure if this is the right place for this question.

We used the MCM rest API for some time now, but it lately returns empty results, see e.g. 
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/produces/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM 

-> {"results": {}}
This request worked some time ago.
Did something change in the way MCM should be accessed ?

best,
Tobias

**Comment by anorkus** [comment]
hi,

it works for sure, example:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/produces/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIISpring15MiniAODv2-Asympt50ns_74X_mcRun2_asymptotic50ns_v0-v1/MINIAODSIM

 Are you searching for the correct/existing output which was produced with McM? I can see only 5 requests with similar dataset:
https://cms-pdmv.cern.ch/mcm/requests?produce=*ZZTo2L2Nu_13TeV_*&page=0&shown=268435471

**Comment by anorkus** [comment]
never mind. found the request:
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIISpring15MiniAODv2-00249&page=0&shown=11005853823

seems somehow its output_dataset was not registered and your results are 0

**Comment by tobias-pook** [comment]
Hi, 
thanks for your reply. I am still not sure that there is no issue. I build some tools to populate our custom n-tuple database in Aachen EXO groups if users create them with crab. MCM was always used during this process and it worked for some time now without any problems. Today 2 users contacted me that the tool crashes due to empty MCM entries ( error handling could have been better here on my side (-; ). The sample I used in my initial request was used in a small test script for our MCMreader class and I'm sure it worked in the past. There is no problem to run on the samples using crab, so I guess they should be in MCM.

Here are the 2 samples the uses tried to work on, which also produce empty output:
/ZToMuMu_NNPDF30_13TeV-powheg_M_800_1400/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM

/DYJetsToNuNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM

**Comment by anorkus** [comment]
ok, i've force updated those two request's and now produces returns data ;)
thanks for spotting and reporting this

**Comment by padeken** [comment]
Wait a moment this is not only a problem with these two samples there are much more that are not reachable. A small test (not complete):

/WprimeToENu_M-3800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-4000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-4200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-4400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-4600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-4800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-5000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-5200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-5400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-5600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToENu_M-5800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-1000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-1200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-1400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-1600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-1800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-2000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-2200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-2400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-2600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-2800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-3000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-3200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-3400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-3600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-3800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-4000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-4200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-4400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-4600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-4800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-5000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v3/MINIAODSIM
/WprimeToMuNu_M-5200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-5400_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-5600_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToMuNu_M-5800_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-1000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-1200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-1400_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-1600_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-1800_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM
/WprimeToTauNu_M-2000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-2200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-2400_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-2600_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-2800_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-3000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-3200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-3400_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-3600_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-3800_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-4000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-4200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-4400_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-5200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-5400_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-5600_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTauNu_M-5800_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToENu_M-1000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToENu_M-200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToENu_M-3000_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToENu_M-500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToTauNu_M-1000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToTauNu_M-200_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToTauNu_M-200_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToTauNu_M-3000_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WToTauNu_M-500_TuneCUETP8M1_13TeV-pythia8-tauola/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_1000to1400_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_10to15_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_1400to1800_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_15to30_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_170to300_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_1800to2400_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_2400to3200_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_3200toInf_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_5to10_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_800to1000_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_120_200/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_1400_2300/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_200_400/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_2300_3500/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_3500_4500/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_400_800/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_4500_6000/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_50_120/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_6000_Inf/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZToEE_NNPDF30_13TeV-powheg_M_800_1400/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DYJetsToLL_M-500to700_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v3/MINIAODSIM
/TT_Mtt-1000toInf_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2_ext1-v1/MINIAODSIM

**Comment by anorkus** [comment]
yeah, noticed that :( there is 2.5k there is a 'logical bug' in how completed events/output dataset is checked/updated when the output_dataset construction algorithm changes.

**Comment by tobias-pook** [comment]
Hi,
I'm glad you now see that there is an issue, I was a bit worried when you closed the issue without confirmation.
I wrote a small skript which tested entries for all datasetpath returned by the das_client query:
dataset=/*/*RunIISpring15MiniAODv2-74X_mcRun2_*/MINIAODSIM

I found about 2000 missing entries for 4491 tested datasetpath. So about half of all samples from the production campaign all our groups use are not available.

This is a serious issue for us because our workflow relies on McM in some parts and we have to check entries by hand otherwise, which is not feasible given the large numer of samples to handle.
Output:
/afs/cern.ch/user/t/tpook/public/missingInMCM.txt

Script:
/afs/cern.ch/user/t/tpook/public/testMCM.py

**Comment by anorkus** [comment]
hi,

i've updated -prod instance of mcm. And ran force update on troublesome requests. Can you check on you side if you have other data.
Also, i tried to run your testMCM script (simple 'python testMCM.py' command), killed after 1h without any output, does it take so long or i didnt set up something?

**Comment by tobias-pook** [comment]
Hi,
Thanks ! Yes the script takes very long. I will try to run it again and 
report the output.

best
Tobias

**Comment by tobias-pook** [comment]
Hi,
here are the results from my script. Most samples seem ok now. 

sample not in db:
/DM_PseudoscalarWH_Mphi-50_Mchi-1_gSM-1p0_gDM-1p0_13TeV-JHUGen/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v3/MINIAODSIM
/GG_M-300To750_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2G_M-260_narrow_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WJetsToLNu_HT-800To1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2_ext1-v1/MINIAODSIM
/ZprimeToA0hToA0chichihAA_2HDM_MZp-1700_MA0-300_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZprimeToA0hToA0chichihAA_2HDM_MZp-2000_MA0-300_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM

sample with http error ( would probably work on second try):
/AxialMonoW_Mphi-10_Mchi-10_gSM-1p0_gDM-1p0_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BBbarDMJets_scalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH2_MD-6000_MBH-10000_n-4_TuneCUETP8M1_13TeV-blackmax/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH2_MD-8000_MBH-10000_n-2_TuneCUETP8M1_13TeV-charybdis/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH4_MD-7000_MBH-9000_n-4_TuneCUETP8M1_13TeV-charybdis/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH5_MD-5000_MBH-6000_n-4_TuneCUETP8M1_13TeV-blackmax/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH8_MD-4000_MBH-7000_n-2_TuneCUETP8M1_13TeV-charybdis/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DMV_NNPDF30_Vector_Mphi-100_Mchi-100_gSM-1p0_gDM-1p0_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DMV_NNPDF30_Vector_Mphi-200_Mchi-1_gSM-0p25_gDM-1p0_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DisplacedSUSY_StopToBL_M-1100_CTau-1000_TuneCUETP8M1_13TeV_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/GluGluToZZTo2e2mu_BackgroundOnly_13TeV_MCFM/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/TprimeTToBW_M-1700_TuneCUETP8M1_13TeV-madgraph-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM
/VBFHToBB_M125_13TeV_amcatnlo_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WminusH_HToZZTo4L_M125_13TeV_powheg-minlo-HWJ_JHUgen_pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToWZToWhadZlep_narrow_M-3500_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToWhToWhadhbb_narrow_M-1200_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToWhToWlephbb_narrow_M-1200_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/X53X53_M-1300_RH_TuneCUETP8M1_13TeV-madgraph-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM'

sample with other error ( unhandled error produced in my script by these samples.)
/ADDGravToGG_MS-3000_NED-4_KK-1_M-2000To3000_13TeV-sherpa/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ADDdiPhoton_LambdaT-6500_Pt-150To500_TuneCUETP8M1_13TeV-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BBbarDMJets_pseudoscalar_Mchi-1000_Mphi-10_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH2_MD-8000_MBH-9000_n-4_TuneCUETP8M1_13TeV-charybdis/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH5_MD-9000_MBH-11000_n-4_TuneCUETP8M1_13TeV-blackmax/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BlackHole_BH8_MD-3000_MBH-9000_n-2_TuneCUETP8M1_13TeV-charybdis/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/BprimeBprime_M-800_TuneCUETP8M1_13TeV-madgraph-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM
/DMV_NNPDF30_Axial_Mphi-300_Mchi-150_gSM-0p25_gDM-1p0_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DMV_NNPDF30_Axial_Mphi-500_Mchi-10_gSM-1p0_gDM-1p0_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DMV_NNPDF30_Vector_Mphi-50_Mchi-10_gSM-1p0_gDM-1p0_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/DM_PseudoscalarWH_Mphi-2000_Mchi-500_gSM-1p0_gDM-1p0_13TeV-JHUGen/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v2/MINIAODSIM
/DarkMatter_MonoZToLL_A_Mx-1_Mv-1000_gDMgQ-1_TuneCUETP8M1_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2VTo2L2Nu_M-400_narrow_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/RadionToZZToZhadZinv_narrow_M-4500_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/StringBall_MD-1600_MBH-6000_MS-1300_gs-04_n-6_TuneCUETP8M1_13TeV-blackmax/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/VectorMonoW_Mphi-50_Mchi-1_gSM-1p0_gDM-1p0_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WGToLNuG_PtG-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WWTo2L2Nu_13TeV-powheg/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/WprimeToTB_plusSM_TToLep_M-1000_LH_TuneCUETP8M1_13TeV-comphep-pythia8/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM
/ZprimeToZhToZlephbb_narrow_M-1800_13TeV-madgraph/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM'

**Comment by anorkus** [comment]
hi, those 6+1(found one) requests/datasets will be reset and resubmitted. Seems they were submitted without the customisation process_string and mcm cannot find expected output in these wf's so this is not indexed.

connection issues might have came from DB restart today ;)

**Comment by tobias-pook** [comment]
Hi, 
Is the 'logical bug' fixed now ?
If I understood you correctly the issue is fixed for the future and existing broken samples were fixed, am I right ?
The issue can be solved from my point of view if both questions can be answered with yes.

thanks,
Tobias

**Comment by anorkus** [comment]
Hi,

yes, the bug was fixed for any new request even from day 1. Problem was with old requests which were submitted with old methods and now they are fixed.
