### ISSUE TITLE
Need of ProcessString when 2 requests have 2 different configs

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#807]
@anorkus 
I think this issue was solve long ago, but I'm not sure why it comes back.

For example:
EGM-RunIISummer15GS-00008 and EGM-RunIISummer15GS-00015
+ Same dataset name
+ Different cmsDriver (defined in the flow level)
+ ProcessString of 00015 is defined in the flow level
I cannot validate 00015, because of missing of process string. So I have to put one.

Then, manually, I use pdmvserv account to remove process_string out before submission. For example,
for another request which is now in submission, HIG-RunIISummer15GS-01245:
+ pdmvserv_HIG-RunIISummer15GS-01245_00177_v0_magnetOffBS0T_151223_201247_877 (reject)
+ pdmvserv_HIG-RunIISummer15GS-01245_00179_v0__151224_072312_2305 (remove process_string manually)

**Comment by anorkus** [comment]
hi,

well issue is here:
https://github.com/cms-PdmV/cmsPdmV/blob/11812ad45fa516e0c73291e69386bbbd98231b30/mcm/json_layer/request.py#L323
when checking before validation process_string is not constructed, but taken directly from request parameters.
