### ISSUE TITLE
Same check for dataset name as computing should be implemented in McM

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#808]
As reported here,
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/2387.html

McM should have the same check for computing for dataset name (length+characters), to avoid issue of injection.

**Comment by vlimant** [comment]
Note https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/json_layer/request.py#L224

**Comment by srimanob** [comment]
So we are missing "+" :)
