### ISSUE TITLE
missing input dataset in submitted request

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/cmsPdmV#814]
https://cms-pdmv.cern.ch/mcm/requests?produce=%2FQCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8%2FRunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1%2FMINIAODSIM&page=0&shown=1048703

we know  that the dataset 
/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM

produced by SUS-RunIIFall15MiniAODv1-00001   

has this: 
https://cmsweb.cern.ch/das/request?input=parent%20dataset%3D/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIFall15MiniAODv1-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM&instance=prod/global&idx=0&limit=10 

as parent.

Despite that, the parent is not shown.
Same problem found also for SMP-RunIIFall15MiniAODv1-00002 and SUS-RunIIFall15MiniAODv1-00002

**Comment by anorkus** [comment]
emm. with miniAODv1 you expect 1 datatier:
--datatier MINIAODSIM
thats why only one is registered. AODSIM/DQMIO was produced in DR step:
https://cms-pdmv.cern.ch/mcm/requests?produce=%2FQCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8%2FRunIIFall15DR76-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1%2FAODSIM&page=0&shown=268435583
