### ISSUE TITLE
glideinWMS monitor link in McM

### ISSUE THREAD

**Issue by perrozzi** [cms-PdmV/cmsPdmV#815]
I would like to know if is possible to add a link in McM to the glideinWMS monitor,
for each workflow. They might be good for monitoring purpose, I have seen the links being sent around especially by Jean-Roch while answering to questions in HN
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/2404/1.html

**Comment by perrozzi** [comment]
Hi, thanks a lot. May I kindly ask how to access the info? I don't see (yet?) any button on McM.
Thanks again!
Luca

**Comment by anorkus** [comment]
hi,

for now it's in -dev instance only. It could appear tomorrow in -prod. Could means that there was a huge change in mcm internal code and i might not pull everything tomorrow. Also want to check something before pulling a new version.

**Comment by anorkus** [comment]
updated -prod instance. the link is under a 'bell' icon in 'Reqmgr name' column
