### ISSUE TITLE
Registering StepChain workflow type as valid workflow

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#818]
This workflow

https://cmsweb.cern.ch/reqmgr/view/details/dmason_task_SMP-RunIIWinter15wmLHE-00075__v1_T_HEPCloud_160206_052227_4617

is not getting attached to 

https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-RunIIWinter15wmLHE-00075

**Comment by anorkus** [comment]
registered now. Should it be force closed?
