### ISSUE TITLE
please add a field in the generator parameters for the fraction of negative weights

### ISSUE THREAD

**Issue by perrozzi** [cms-PdmV/cmsPdmV#820]
please add a field in the generator parameters for the fraction of negative weights
this is a very important parameter that is necessary to properly compute the integrated luminosity and the total number of events

**Comment by srimanob** [comment]
I think @anorkus has added the field, as he showed me yesterday.
Could you please provide the time scale to have it in prod, @anorkus ?

**Comment by anorkus** [comment]
tuesday most likely ;)

**Comment by perrozzi** [comment]
thanks really a lot for the prompt action! :-)

**Comment by anorkus** [comment]
pulled with newest release to -prod

**Comment by perrozzi** [comment]
Dear Antanas,
thanks really a lot.
I have a question, just to make sure: does the negative weights fraction number gets updated automatically with the validation or not? I assume not

Thanks again
Luca

**Comment by anorkus** [comment]
Hi,

for now not: just a field which can be filled by user and nowhere used in calculations. Do you need it to be updated from framework job report after validation?

**Comment by perrozzi** [comment]
Hi, I would say that for the moment is ok like this.
thanks again
