### ISSUE TITLE
pileup (in campaign definition) and premixing

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#823]
If we setup the campaign with "pileup" parameter (as in Fall15DR76), we will have issue with premixing. This is because in premixing, we don't see "pileup" in DIGI step since the PU scenario is used already in premix MB step. So we need to delete pileup out from the configuration manually. 

It seems to me that we can't set pileup = '' in the flow level also, as McM will then disable --pileup_input:
https://github.com/cms-PdmV/cmsPdmV/blob/abc23e8da40e843b38213bf17fa09af18cedd171/mcm/json_layer/campaign.py#L100-L101

**Comment by anorkus** [comment]
so we could change to check only if pileup is set to 'NoPileUp'  we do not set the pileup_input. Do we have many sequences with pielup='' where pileup_input has to be excluded?
