### ISSUE TITLE
Tag for ticket

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#829]
Can we have Tag for ticket also? I think it will be very useful for GEN contact to use it to group their tickets as now tickets are created from them.

**Comment by anorkus** [comment]
-prod DB needs migration for all mccms to have tags:[] as default. Could be done on tuesday before new version. Should take 5-10mins.

**Comment by srimanob** [comment]
I've seen that Tag appears in ticket now. However, when I tried to add tag, then commit. After viewing, tag is missing.
https://cms-pdmv.cern.ch/mcm/mccms?prepid=B2G-2016Apr20-00001&page=0&shown=21607
