### ISSUE TITLE
Display dataset name close to root requests and total stats for tickets

### ISSUE THREAD

**Issue by perrozzi** [cms-PdmV/cmsPdmV#833]
Hi,
if possible I think it would be nice to display the dataset names close to the root request prepid in the tickets. Also the total stats of the ticket would be good to have (with the caveat that the ROOT requests usually have more events than the rest of the chain)

Thanks
Luca

**Comment by srimanob** [comment]
It may need to rethink about the ticket. As a range can be used for ticket, i.e. 00001 - 00100. If this is the case, we can overload MccM to try to load 100 requests at once.

**Comment by perrozzi** [comment]
We discussed during the pre-mccm last week to put at least the total stats associated to the ticket, @anorkus might be working on that soon
also, I understand that the visualization of the requests associated with a ticket is done throuhgh
requests?range=...
I wonder if a "page-like" system could be used to avoid loading 100+ requests at the same time
ciao
luca

**Comment by srimanob** [comment]
In fact, their is one field called size which should represent what you want,

From the glossary, mccms size is an indication of the total amount of events expected in the end (repetitions times chains times requests times ...)
