### ISSUE TITLE
hook for force-completing / bypassing

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#837]
there is a hook in unified to set force-complete and bypass statistics checks.
can we please have a button somewhere to set an entry in a separate table for workflows that need force complete/bypass (similar to invalidations operation) ?
if you make a forcecomplete table with new/done status. an api for unified to acknowledge (new->done) then I'll wire this in Unified for ease of operation.

@srimanob

**Comment by trandbea** [comment]
+1 for making this available to gen contacts!

**Comment by scasasso** [comment]
+1

**Comment by duanders** [comment]
+1

**Comment by alkaloge** [comment]
+1

**Comment by anorkus** [comment]
@vlimant when using https://cms-pdmv-dev.cern.ch/mcm/restapi/requests/forcecomplete will return list of workflows.
If you want them to 'acknowledge' curl -X DELETE -s -k https://cms-pdmv-dev.cern.ch/mcm/restapi/requests/forcecomplete/B2G-RunIISpring16DR80-00033 will remove specified request from force complete list.
Do you need any other information returned?

**Comment by vlimant** [comment]
nice ! who has access to these url

**Comment by anorkus** [comment]
gen_contacts & same people to acknowledge invalidations. You might try to do copy/paste the curl command i've sent to see if it works for you

**Comment by vlimant** [comment]
Are you keeping a track in mcm history of who requests force-completion ? 

Could the first call be a dictionnary of prepid : { user : [wf1, wf2] }

the prepid in the delete call corresponds to the mcm prepid, or the wf prepid (they are different for taskchains)

**Comment by anorkus** [comment]
yes i track in request history for the force completion.
Why do you need the user info in the return data?
the prepid corresponds to requests prepid on which the force complete was requested. This shouldn't matter for taskchain as when forcecomplete was acknowledged; the workflow will go to announced and and the corresponding requests in mcm will go to done.

**Comment by anorkus** [comment]
also the return of force complete returns last workflow registered to request - as the last one is always the running one. this is fine with you?
because the dictionary always would be prepid:{user:[wf1]}

**Comment by vlimant** [comment]
no real need for user, that was just for logging purpose, if mcm has a track, it's fine.
the last wf name is not really what is relevant, it's not always the last running.
there is difference of request-prepid and workflow-prepid to find what corresponds to what.

I vote for having only the mcm-prepid returned in the list, no need for wf name

**Comment by anorkus** [comment]
in -prod since today morning

**Comment by vlimant** [comment]
hooked in Unified https://github.com/CMSCompOps/WmAgentScripts/commit/33b5604d390bbc7cfadb65531097279663a78baf

**Comment by anorkus** [comment]
also:
https://cms-pdmv-dev.cern.ch/mcm/restapi/requests/forcecomplete

now returns a list or mcm request prepids.

**Comment by trandbea** [comment]
Dear Antanas, can you add a dialog that requires confirmation like for the approve icon? This is dangerous enough I would not want to click it on accident while targeting a neighboring small icon. Thanks!

**Comment by trandbea** [comment]
I tried this on two requests:
https://cms-pdmv.cern.ch/mcm/requests?prepid=SUS-RunIISpring16DR80-00078
https://cms-pdmv.cern.ch/mcm/requests?prepid=SUS-RunIISpring16MiniAODv1-00078
They do not appear in the forcecomplete list, I don't see the attempt in McM history and I didn't get any email. I did see a confirmation on the bottom of the screen after clicking. Is this consistent with what you expect? I.e. the action would only appear sometime later when it's taken effect?

**Comment by vlimant** [comment]
@trandbea I can see the two prepids in the restapi
https://cms-pdmv.cern.ch/mcm/restapi/requests/forcecomplete
in fact, I had to do more dev on Ops end to force complete something that is in recovery.

**Comment by anorkus** [comment]
@trandbea https://github.com/cms-PdmV/cmsPdmV/commit/7a7a8100bdb0b064f02ebd602f96392b00f0c581 adds the confirmation pop-up. 
The history was updated, but you needed to reload the page (requests) to see the change, with this commit it will reload after successful addition to force complete list.

**Comment by trandbea** [comment]
@anorkus Thanks! I just had to use it again and I see the pop-up. Feeling much safer in McM land again :)

**Comment by vlimant** [comment]
because people might ask for force-complete while the workflow is already being send out, and because mcm might not be reachable at all times, entries can stay in https://cms-pdmv.cern.ch/mcm/restapi/requests/forcecomplete and would have to be cleaned up somehow. Do you want to have something internal that removes it from the it when toggling to "done", or should unifed/ops have something that polls and acknowledge anything irrelevant anymore ? I vote for the first for consistency ;-)

**Comment by vlimant** [comment]
/restapi/requests/forcecomplete/EXO-RunIISpring16DR80-02248
/restapi/requests/forcecomplete/EXO-RunIISpring16DR80-02239

 does not seem to make the entry go away, so it's eternally force-completing...
