### ISSUE TITLE
search panel in the MCM homepage

### ISSUE THREAD

**Issue by govoni** [cms-PdmV/cmsPdmV#842]
To whom it may concern, I would like to suggest that the navigation/search panel which appears when prompting a list of requests appears also in the homepage of MCM: several people, when confronted with MCM at the first time (for example searching for the settings of a produced sample) don't know what to do, since there's nothing "doable" for them in the homepage.
pietro

**Comment by rtcharly** [comment]
Hi Pietro,

Are you talking about this panel? 
![captura de pantalla 2017-02-22 a la s 13 03 05](https://cloud.githubusercontent.com/assets/9299048/23210777/6309385c-f8ff-11e6-9e65-cea3c5cc008d.png)

If yes, could you please specify which fields you would like to appear in that panel.

Roberto Rivera

**Comment by govoni** [comment]
Dear Roberto,

yes I refer to that.
I find that at least the following might be useful:
- prepid
- dataset_name
- tags
- ticket name

where the last one is a new one.

Best regards,

pietro

**Comment by anorkus** [comment]
and you would like to search the requests page via this panel?
ticket_name would be more interesting, as its inside the tickets page not requests and mixing searches of multiple pages might be tricky

**Comment by govoni** [comment]
if I want to search for a request now I do use that panel, but I have to dig it out by going to a single person list of requests, until it appears.
I just find that the panel should stay in the homepage as well, otherwise it's like google w/o the search window in the main page ;)

**Comment by rtcharly** [comment]
Dear Pietro,

I want to clarify a few things, the first two fields are from requests and the last one is from mccm ticket (prepid), by dataset_name you mean input dataset_name or output_dataset?. the field "tags" it is in both requests and mccm tickets, if the user writes something in that field, what should I search? requests or mccm tickets?. Last question, if the user types something in prepid field and also types something in ticket name, what should I show? requests or mccm ticket?

Best,

Roberto Rivera

**Comment by govoni** [comment]
Dear Roberto,

I think that the best is to exactly do what the search panel already does, since in these cases consistency is very important: you don't want that a search, which looks the same, behaves differently is performed from two different places.
Couldn't you simply copy-and-paste the code for the other search to the main page?

Best regards,

pietro

**Comment by rtcharly** [comment]
Ok, I'll do that, thanks!

**Comment by govoni** [comment]
thanks!

**Comment by govoni** [comment]
I saw the panel, it's very useful, thanks! Once you'll have the tickets as well it will be great!
