### ISSUE TITLE
Set Campaign in TaskChains

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#850]
allow me to reopen the Pandora box
can we have Campaign be set by tasks from McM, in addition to acquisitionera (agreed that they are the same values) so that they can be treated differently when dealing with relvals (where they can be different)

**Comment by vlimant** [comment]
hold on while I get confused ...

**Comment by anorkus** [comment]
we do that already all the time;) i though this issue would come again and when asked to add AcquisitionEra i've added and and kept Campaign.

**Comment by vlimant** [comment]
neither 
https://cmsweb.cern.ch/reqmgr2/data/request?name=fabozzi_RVCMSSW_9_0_0_pre4RunDoubleMuon2016B__testUnif_RelVal_doubMu2016B_170224_111324_8585
nor 
https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_task_SUS-PhaseIFall16DR-00007__v1_T_170222_125846_8911

do have Campaign set in each *Task* and I would make lots of sense. 
in McM because then otherwise there is only one campaign that is set while the workflow contains many, and Unified would rely on it (Campaign) to know what is what. 
for Reval they (campaign and acquisitionera) will be different and specifiying campaign per task would help treating things uniformly.

Maybe Campaign is only allowed at a top level parameter, @amaltaro ?

Still looking into the details, let's not close GH issue just to not have any opened for the week-end

**Comment by anorkus** [comment]
well mcm was setting Campaign only of top level since day0 of taskchains and acquisitionEra for internal dictionaries. That was your original code

**Comment by vlimant** [comment]
things change.

**Comment by anorkus** [comment]
why would you need that if the campaigns (placeholder for batches) would be used only for the workflows searches(?) and not the inside tasks?

**Comment by vlimant** [comment]
The campaign would be used to defined a certain computing configuration in all cases.
AcquisitionEra labels the output dataset. in mcm case it's the same, for relval there is a difference and we need the same syntax everywhere for unification, I think.
because things were handled in different pipes before it did not matter to have a unique "profile", while we are trying to get there now.

**Comment by anorkus** [comment]
fyi: https://github.com/cms-PdmV/cmsPdmV/commit/c134b9b0f987409b6720b45eb617c3d8be292929
will go to production next week

**Comment by vlimant** [comment]
great ! it turns out to be a major pain in the neck to not have them both for all (relval, mcm) chains
