### ISSUE TITLE
Remove prepid from force-complete list

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#865]
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-PhaseIIFall16LHEGS82-00018
see history

was forcecompleted, then resubmitted, and because the prepid is not removed from the forcecomplete list, it got re-forcedcompleted. (last comment on #837) 
FYI @areinsvo @mcremone

**Comment by vlimant** [comment]
https://its.cern.ch/jira/browse/CMSCOMPPR-817

**Comment by rtcharly** [comment]
Hi @vlimant , I just removed the request from the list, Could you please check?

**Comment by vlimant** [comment]
That works for this one indeed, thanks.
We should find a way to have it removed from the list by itself.

**Comment by rtcharly** [comment]
Yes, there is already a DELETE http method which you can use like so: https://cms-pdmv-dev.cern.ch/mcm/restapi/requests/forcecomplete/<pid>, although we can also put a button in the UI  to invoke it if you want

**Comment by vlimant** [comment]
as mentioned in #837, it'd be better if this was done internally to McM, to avoid to rely on a hard handshake between services
