### ISSUE TITLE
Set time/event along the same convention of reqmgr

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#868]
it appeared to me today that (https://cms-pdmv.cern.ch/mcm/settings?prepid=timing_method) AvgEventTime is used to set the time per event and according to https://github.com/dmwm/WMCore/issues/7767 this is not the right value (only valid in single thread mode).

Convention in reqmgr2 and mcm should be aligned so as to have more accurate job splitting.
Can 1/EventThroughput be used instead ?

**Comment by anorkus** [comment]
so single_core: AvgEventTime
multicore: 1/EventThroughput

why not a 1/EventThroughput method for both?

**Comment by vlimant** [comment]
1/EventThroughput for all indeed

**Comment by anorkus** [comment]
since which CMSSW release EventThroughput is available? as this option might not be available for all campaigns.

as this test https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/EXO-RunIISummer15GS-03142
xml doesnt have EventThroughput reported

**Comment by vlimant** [comment]
Crap ... we might have to fallback to avgeventtime * ncore for campaigns in old release. It is likely that all such releases do not support multicore anyways, so it might not be event necessary to grab the ncore from configuration and just use avgeventtime.

Please judge whether you can deploy such change quick enough that it will be worth for long enough. 
We might change the reqmgr2 convention a couple of month from now, and just change the mcm setting at that time.

**Comment by anorkus** [comment]
so this boils down to use two metrics:
1) 1/EventThroughput where possible
2) AvgEventTime* nCore for fallback

correct?
will be hard for people to find out which method was used and bring more confusion.

**Comment by anorkus** [comment]
fyi: https://github.com/cms-PdmV/cmsPdmV/commit/e9ba9dbbbaac68258299c7105ef3a7b7a25a1420

will go to production tomorrow.

**Comment by vlimant** [comment]
@anorkus can you please confirm this actually made it in production ?

**Comment by anorkus** [comment]
@vlimant yes. this can be seen in the release tag notes of mcm
