### ISSUE TITLE
synchronisation of priority should not be applied to Resubmission type request

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#888]
looking at https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-PhaseIITDRFall17wmLHEGS-00025
it looks like an mcm service went on and decreased the priority of 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_ACDC0_task_SMP-PhaseIITDRFall17wmLHEGS-00025__v1_T_171116_110914_3600
preventing from taking over and completing. 

Please do not sync the priority of ACDC (Resubmission type) workflows

**Comment by vlimant** [comment]
does not look like it happened again. was this removed ?

**Comment by vlimant** [comment]
@anorkus any simple way to get this done ?

**Comment by justinasr** [comment]
Shouldn't be too hard to implement. Just avoid workflow names that contain "ACDC"? Are there any other conditions?

**Comment by vlimant** [comment]
no other conditions no. thanks @justinasr for looking into this
