### ISSUE TITLE
Problems fetching info for GenOnly campaign with McM scripting

### ISSUE THREAD

**Issue by jotadram6** [cms-PdmV/cmsPdmV#900]
I would like to kindly ask about the following issue posted on prep-ops hypernews:

https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/5267/1.html

**Comment by justinasr** [comment]
Issue solved in hypernews. User was using dev McM instead of production.
Dev is `mcm = restful(dev=True)`. Production is `mcm = restful(dev=False)`.
