### ISSUE TITLE
Fix JSON output of McM API

### ISSUE THREAD

**Issue by vkuznet** [cms-PdmV/cmsPdmV#934]
I found that request to McM restapi does not return a proper JSON output. Please have a look at this API:

https://cms-pdmv.cern.ch/mcm/public/restapi/requests/produces/BBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM

It returns a string representation and not a real JSON data-structure. In particular the raw bytes which I read in Go looks like this:
```
"{\n    \"results\": {\n        \"total_events\": 300300, 
....
\n        \"generators\": [\n            \"\\\"pythia6\\\"\"
....
```
The problem is that you're trying to escape symbols instead of using `json.dumps` python method. To prove this please have a look at this python snippet:
```
>>> data={"data":"\"bla\""}
>>> type(data)
<type 'dict'>
>>> print(data)
{'data': '"bla"'}
>>> import json
>>> json.dumps(data)
'{"data": "\\"bla\\""}'
```
Here I created a data with double quotes. The `json.dumps` API properly dump it as a string which contains 2 (!) slashes, while in your dump (shown above) you provide generator with 3 (!!!) slashes. This cause a JSON parser (in this case Go json) to fail to parse your data.

I saw these type of errors in MANY CMS systems where people use `print` function instead of `json.dumps` to return json representation of their objects.

This problem cause DAS to fail on mcm queries and here is relevant DAS ticket: https://github.com/dmwm/DAS/issues/4295

Please fix your APIs and provide proper JSON representation of your objects.

**Comment by vkuznet** [comment]
Here is an another example of mixing python strings and json objects:
```
>>> data="""{\n"data":\n"bla"}"""
>>> print(data)
{
"data":
"bla"}
>>> import json
>>> print(json.dumps(data))
"{\n\"data\":\n\"bla\"}"
>>> o=json.dumps(data)
>>> json.loads(o)
u'{\n"data":\n"bla"}'
```
when I load data which I "think" I created as JSON it is loaded as string and not as JSON.

**Comment by justinasr** [comment]
Changed Content-Type of returned data to application/json.

**Comment by heitorPB** [comment]
Is this fix already deployed to production?

**Comment by justinasr** [comment]
Yes.

**Comment by vkuznet** [comment]
It is not issue of McM anymore, dasgoclient needs a change to use proper content
type. Since DAS server was patched and propagated to production I can update
dasgoclient now. The fix will appear tonight in CMSSW.
