### ISSUE TITLE
preventing req. managers approving non-GEN approved requests

### ISSUE THREAD

**Issue by efeyazgan** [cms-PdmV/cmsPdmV#947]
We have a few cases in the last year or so that request managers approved by mistake some requests before GEN review. What would be the best way to prevent these cases without causing too much inconvenience to requests managers and GEN conveners?

Related to this:
We agree that if a request is cloned from a different campaign, it should definitely require GEN approval. What to do if it's cloned from the same campaign?

**Comment by efeyazgan** [comment]
@qliphy

**Comment by vlimant** [comment]
req manager should keep having uber privileges ; and should use them with care
