### ISSUE TITLE
Filter efficiency check in validation

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#960]
Filter efficiency should be checked when validation runs. If it's not within the uncertainty, validation should fail. It seems not implemented.

The same should happen for matching efficiency.

Example: 

https://cms-pdmv.cern.ch/mcm/requests?prepid=BPH-PhaseIIMTDTDRAutumn18GS-00004&page=0&shown=127

Real filter efficiency is 0.058, it was submitted with 0.00085, given by MC contacts

@justinasr

**Comment by pgunnell** [comment]
High priority!

**Comment by vlimant** [comment]
good to follow up indeed. This runtest of the efficiency used to be there, and it seems to be there 64811d778a090ee13100b53092463709429b0597 but indeed how did that BPH request go through ?

**Comment by justinasr** [comment]
I'm not sure I understand the problem. Generator parameters in McM [1]: `filter efficiency 0.058` (edited 6th of February, 2019). If I look in ReqMgr2 [2], I see 0.058 too: `"FilterEfficiency": 0.058`. @pgunnell where do you see that it was submitted with 0.00085? @vlimant you're right, efficiency is checked, some time ago we updated the formula (link that you provided)

[1] https://cms-pdmv.cern.ch/mcm/requests?prepid=BPH-PhaseIIMTDTDRAutumn18GS-00004&page=0&shown=137440002049
[2] https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BPH-PhaseIIMTDTDRAutumn18GS-00004__v1_T_190213_125323_7924

**Comment by pgunnell** [comment]
Hi Justinas, yes, because I resubmitted the sample with a new efficiency. Before it was 0.00085.

**Comment by pgunnell** [comment]
The problem is sigma! if the filter efficiency is too low, then the value is taken as 0.025 which is definitely too high and requests can pass validation

**Comment by pgunnell** [comment]
https://github.com/cms-PdmV/cmsPdmV/blob/master/mcm/json_layer/request.py#L2165

**Comment by justinasr** [comment]
Ok, so we agreed on using this:
```
if (sigma < measured_efficiency * 0.02):
    sigma = measured_efficiency * 0.02
```
