### ISSUE TITLE
Add a note in the requests of a chain if workflow is rejected in computing and not resubmitted

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#964]
Middle priority -> This helps the monitoring a lot

If a request is rejected by computing and not resubmitted within 5 days (we can tune this number), the requests of the chain get a label in the Notes column that the workflow has been rejected.

**Comment by justinasr** [comment]
And status is left untouched (submit-submitted)?

**Comment by pgunnell** [comment]
Yes (you said you don't want to touch the status no?).

If you want to add one status, then would be best, otherwise a note would be good

**Comment by justinasr** [comment]
A new status would be submit-rejected? Can requests with this status be reset?

**Comment by pgunnell** [comment]
yes and yes!

**Comment by justinasr** [comment]
Update: we agreed on adding a note on "dead" requests. Also add a note if request is `submitted`, but workflow stays in `new` for too long.

**Comment by pgunnell** [comment]
For reference:
https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?in_disagreement=1

**Comment by vlimant** [comment]
extremely bad idea to add a new status like submitted-rejected to track unrecoverable issue.
the "dead" label was also an extremely bad idea.

a reset and delete (or fix) is a better option anytime of the day.

**Comment by ggonzr** [comment]
Substituted by: [#20](https://gitlab.cern.ch/cms-ppd/dataset-management/dm-coordination/-/issues/20)
