### ISSUE TITLE
Update of number of events in McM from invalidated requests in computing

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#966]
Middle priority:

synchronise the number of events in McM with the valid DAS dataset.

Currently, McM sums up valid and invalid number of events (and consequently gets >100%).

**Comment by justinasr** [comment]
Any examples?

> Currently, McM sums up valid and invalid number of events (and consequently gets >100%).

**Comment by pgunnell** [comment]
Hi Justinas, I can not find any example actually, it seems that the problem is already fixed?

**Comment by justinasr** [comment]
Was this for expected events or produced (completed) events? Recently Stats got an update for expected events, so that may have fixed something.

**Comment by pgunnell** [comment]
This was for completed events. ok, we can close the issue and apply no modifications!
