### ISSUE TITLE
Add a link in DAS to McM

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#968]
Low priority: just for record to be followed up. (result of the survey)

Add a link in DAS to McM (link from MCM to DAS)

**Comment by justinasr** [comment]
> Add a link in DAS to McM (link from MCM to DAS)

So link in McM to DAS or link in DAS to McM?
If latter, then this is an issue to DAS team.

**Comment by vlimant** [comment]
there's a valid das query for this https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=mcm+dataset%3D%2FQED_tautau_atauPlus1_TuneCP5_5p02TeV_UPCgen_pythia8%2FHINPbPbAutumn18pLHE-103X_upgrade2018_realistic_HI_v11-v1%2FLHE

issue for das can be opened there https://github.com/dmwm/das2go/issues

**Comment by lmoureaux** [comment]
Not as user-friendly as a link directly in McM though

**Comment by vlimant** [comment]
will require https://gitlab.cern.ch/cms-ppd/technical-support/ts-coordination/-/issues/1 anyways
