### ISSUE TITLE
Issue with lower release version (block HLT UL)

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#969]
I try to setup the campaign in McM-dev (from scratch to Reco with HLT using original version)
https://cms-pdmv-dev.cern.ch/mcm/chained_requests?contains=PPD-RunIIUL2017GS-00001&page=0&shown=15

I can't make the full flows because of
"Request RunIIUL2017HLT has lower release version.."
requests is reserved upto DIGI step only.

The issue comes from
https://github.com/cms-PdmV/cmsPdmV/blob/bb9b1522e8bdfad65003167017380908929adcb7/mcm/json_layer/chained_request.py#L477-L479

**Comment by justinasr** [comment]
So there should be no check for lower CMSSW version?

**Comment by srimanob** [comment]
It uses to be true. However, for ultra-legacy processing, we expect to use lower CMSSW version for HLT step, see testing here:
https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRunIIUltralegacyPreparationTrigger

I think we should not allow by default, but maybe a button on campaign to tick (by intention) that this should allow to happen).

**Comment by justinasr** [comment]
Maybe on chained campaign? Something `ignore lower CMSSW versions`?

**Comment by srimanob** [comment]
+1 Thx

**Comment by srimanob** [comment]
@pgunnell @justinasr  I would like to have this as high priority fix, as we should inject the pilot of full campaign very soon (based on 10_4 prod release).
