### ISSUE TITLE
Status of request with transient output

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#973]
Test with transient output success,
https://cms-pdmv.cern.ch/mcm/chained_requests?contains=PPD-RunIIFall18wmLHEGS-00007&page=0&shown=15
but status of wmLHEGS is still in submitted, while others are done.

**Comment by justinasr** [comment]
Note to myself: McM says `One of the expected tiers ['GEN-SIM', 'LHE'] has not been produced`. McM needs to ignore datatiers from TransientOutputModules.
