### ISSUE TITLE
Requests with duplicated outputs

### ISSUE THREAD

**Issue by anirban1982** [cms-PdmV/cmsPdmV#974]
If a root request is appeared in two different tickets with the same chain, while submission, it does not check if the root request is already submitted or not with the same chain.

Computing reported such cases, like the following reported in JIRA:

https://its.cern.ch/jira/browse/CMSCOMPPR-4878

For now I have cleaned, and deleted one of the chain completely from mcm and submitted the other one.

**Comment by justinasr** [comment]
It is no longer allowed to create chain request with same root request and chained campaign, #1031
