### ISSUE TITLE
McM allows production of samples with same dataset name and same extension

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#975]
Middle priority - bug

McM allows production of samples with same dataset name and same extension.

https://cms-pdmv.cern.ch/mcm/requests?prepid=*Fall18*&dataset_name=DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8&page=0&shown=32799

This should be forbidden. Does it only come from the fact that the GS output dataset is not kept?

**Comment by vlimant** [comment]
https://github.com/cms-PdmV/cmsPdmV/commit/f9a0eea72101b6c0d64deea310c9827359b03785

**Comment by pgunnell** [comment]
Thanks Jean-Roch! I don't see exactly why this was setup in such way. I would prefer to have always extensions so that the "extX" process string gets propagated to all output datasets.

**Comment by vlimant** [comment]
the protection is already in place
