### ISSUE TITLE
Unable to update generator parameters of GS requests chained to pLHE requests

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#976]
Middle priority - bug:

If a GS request is chained to a pLHE one and the pLHE is done, one is not able to modify the generator parameters, which can not be filled in. 

https://cms-pdmv.cern.ch/mcm/requests?prepid=BPH-RunIIFall18GS-00128&page=0&shown=127

**Comment by justinasr** [comment]
Steps to reproduce?
What I've tried in dev: create a MccM ticket with `BPH-RunIIFall18pLHE-00007` request and `chain_RunIIFall18pLHE_flowRunIIFall18GS_flowRunIIAutumn18DRPremix_flowRunIIAutumn18MiniAOD_flowRunIIAutumn18NanoAOD` chained campaign and then "Generate chains and reserve" or "Generate chains" and then flow it. In both cases generator parameters were editable.

**Comment by pgunnell** [comment]
The problem is when the pLHE is done and it flows to GEN-SIM request. So, it is somehow difficult to reproduce it in dev. You could try to get this chain:

https://cms-pdmv-dev.cern.ch/mcm/chained_requests?prepid=TOP-chain_RunIIFall18pLHE_flowRunIIFall18GS_flowRunIIAutumn18DRPremix_flowRunIIAutumn18MiniAOD_flowRunIIAutumn18NanoAOD-00008&page=0&shown=15

remove all the created steps and see if this happens again when you flow to GS.

**Comment by justinasr** [comment]
> The problem is when the pLHE is done and it flows to GEN-SIM request. So, it is somehow difficult to reproduce it in dev. You could try to get this chain:
> 
> https://cms-pdmv-dev.cern.ch/mcm/chained_requests?prepid=TOP-chain_RunIIFall18pLHE_flowRunIIFall18GS_flowRunIIAutumn18DRPremix_flowRunIIAutumn18MiniAOD_flowRunIIAutumn18NanoAOD-00008&page=0&shown=15
> 
> remove all the created steps and see if this happens again when you flow to GS.

I could not reproduce this in dev with given chain.

**Comment by lmoureaux** [comment]
Could not reproduce 5 years ago and didn't resurface -> closing
