### ISSUE TITLE
Running validation in slc7 for PFCalib and UL campaigns

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/cmsPdmV#985]
(High priority) Validation is failing for requests of RunIIWinter19PFCalib* campaigns, because they need slc7 machines for getting the release, but validation runs on slc6 machines. Error is below:

WARNING: Developer's area is created for architecture slc7_amd64_gcc700 while your current OS is SLC6.

Error out: 
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
curl: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by curl)
curl: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by curl)
curl: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libcurl.so.4)
curl: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libcurl.so.4)
curl: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libz.so.1)
curl: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libssl.so.10)
curl: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libssl.so.10)
curl: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libcrypto.so.10)
curl: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0/external/slc7_amd64_gcc700/lib/libcrypto.so.10)

**Comment by justinasr** [comment]
Did a pull request, running dev validation on CC7 now. If it works, I'll merge the pull request.

**Comment by justinasr** [comment]
Submission fails because vocms081 machine is SLC6.

**Comment by justinasr** [comment]
Still an issue, reopening
