### ISSUE TITLE
Confusing message in efficiency validation failure report 

### ISSUE THREAD

**Issue by grasph** [cms-PdmV/cmsPdmV#989]
Hello,

there is a flaw in,

https://github.com/cms-PdmV/cmsPdmV/blob/7f36be5647ac04a126436361d823b8c80b1343e2/mcm/json_layer/request.py#L2275

which makes the efficiency report a bit confusing. 

I believe `user_efficiency` must be replaced by `measured_efficiency` in the code line quoted above, in order to get a message like:

> McM validation test measured 0.4504 efficiency.
> ...
> User provided efficiency 1.0000 * 0.5000 = 0.5000.
> McM threshold is **0.4504** +- 0.0435.

instead of,

> McM validation test measured 0.4504 efficiency.
> ...
> User provided efficiency 1.0000 * 0.5000 = 0.5000.
> McM threshold is **0.5000** +- 0.0435.

Philippe.

**Comment by justinasr** [comment]
Hello,

Makes sense, easy fix, would not change any logic, @pgunnell what do you think?

**Comment by pgunnell** [comment]
I don't think so, but what is the gain?

**Comment by justinasr** [comment]
No gain. To me, it would make sense as McM measures something and says this is McM's threshold +- 3 sigma

**Comment by pgunnell** [comment]
I tend to think the same. What is the problem @grasph ?

**Comment by grasph** [comment]
The problem is the logic. If I've entered 0.500 and I read that the threshold is 0.500 \pm 0.0435, my first reaction is that the value I entered was correct. If the message says that the boundaries are "0.4504 \pm 0.0435" then I understand immediately why my value was rejected.

**Comment by vlimant** [comment]
logic and message are aligned ; even if a little confusing.

> 0.4504 is not within 0.5000 +- 0.0435.
